---
title: "Localisations"
format: html
editor: visual
---

```{r}
#| echo: false
#| include: false
#| warning: false

library(dplyr)
library(ggplot2)
library(tidyr)
library(readxl)
library(kableExtra)
library(ggpubr)
library(plotly)
library(stringr)
```

```{r}
#| echo: false
#| include: false

human_complete <- read.csv(file = "/Users/anastasialinchik/Desktop/Thesis/DATA/generated/human_new.tsv", header = T, sep = '\t')
human_ptms <- human_complete %>% filter(ptm_class == 'Post-translational')

localisation <- read.csv(file = '/Users/anastasialinchik/Desktop/Thesis/DATA/localisation_raw.tsv', header = T, sep = "\t") %>% dplyr::select(From, GOcellularcomponent) %>% rename(LeadProt = From, loc = GOcellularcomponent)
human_complete <- read.csv(file = "/Users/anastasialinchik/Desktop/Thesis/DATA/generated/human_complete.tsv", header = T, sep = '\t')

oxPTMs <- read_excel(path = '/Users/anastasialinchik/Desktop/Thesis/table_oxPTMs.xlsx', sheet = 'oxPTMs')
oxPTMs <- oxPTMs %>%
  mutate(AAs_list = str_split(Specificity, ", ")) %>% dplyr::select(`Unimod #`, AAs_list) %>% rename(unimod_id = `Unimod #`)

human_ptms_loc <- inner_join(human_ptms, localisation, by = join_by(LeadProt)) %>% separate_rows(loc, sep = "; ") 
human_ptms_loc$loc <- gsub("\\[.*?\\]", "", human_ptms_loc$loc)
```

```{r}
#| eval: false
#| echo: false
df <- human_ptms_loc %>% group_by(loc) %>% summarise(prop = sum(counts_norm_abund_len/sum(human_ptms_loc$counts_norm_abund_len)))%>%
  arrange(desc(prop))

ggplot(df[1:10,], aes(x = reorder(loc,abundance_loc), y = abundance_loc)) +
  geom_col(fill = '#919191') +
  labs(y = 'Proportion of PSM counts', x = 'Localisation') +
  coord_flip() +
  theme_classic(base_size = 13) +
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 11, family = "Lato"),
        axis.text = element_text(size = 11, family = "Lato"),  
        axis.title = element_text(size = 11, family = "Lato"))
```

```{r}
#| echo: false

df <- human_ptms_loc %>% group_by(loc) %>% summarise(abundance_loc = sum(total_counts/256391635))%>%
  arrange(desc(abundance_loc))

ggplot(df[1:10,], aes(x = reorder(loc,abundance_loc), y = abundance_loc)) +
  geom_col(fill = '#919191') +
  labs(y = 'Proportion of PSM counts', x = 'Localisation') +
  coord_flip() +
  theme_classic(base_size = 13) +
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 11, family = "Lato"),
        axis.text = element_text(size = 11, family = "Lato"),  
        axis.title = element_text(size = 11, family = "Lato"))
```

# oxPTMs

What are the most common locations of oxPTMs?

```{r}
df <- human_ptms_loc %>%
  filter(human_ptms_loc$unimod_id %in% oxPTMs$unimod_id & human_ptms_loc$ptm_res %in% oxPTMs$AAs_list) %>% 
  group_by(loc) %>% summarise(abundance_loc = sum(total_counts)) %>%
  arrange(desc(abundance_loc))

ggplot(df[1:10,], aes(x = reorder(loc,abundance_loc), y = abundance_loc)) +
  geom_col() +
  coord_flip() +
  theme_classic()
```

# Oxidation

```{r}
df <- human_ptms_loc %>%
  filter(human_ptms_loc$unimod_id == 35) %>% 
  group_by(loc) %>% summarise(abundance_loc = sum(total_counts)) %>%
  arrange(desc(abundance_loc))

ggplot(df[1:10,], aes(x = reorder(loc,abundance_loc), y = abundance_loc)) +
  geom_col() +
  coord_flip() +
  theme_classic()
```

# Phosphorylation

```{r}
df <- human_ptms_loc %>%
  filter(human_ptms_loc$unimod_id %in% c(21)) %>% 
  group_by(loc) %>% summarise(abundance_loc = sum(total_counts/72596244)) %>%
  arrange(desc(abundance_loc))

# so only 16% of phosphorylations occur in the nucleoplam or the nucleus
ggplot(df[1:10,], aes(x = reorder(loc,abundance_loc), y = abundance_loc)) +
  geom_col() +
  coord_flip() +
  theme_classic()
```

# Acetylation

```{r}
df <- human_ptms_loc %>%
  filter(human_ptms_loc$unimod_id == 1) %>% 
  group_by(loc) %>% summarise(abundance_loc = sum(total_counts/5662533)) %>%
  arrange(desc(abundance_loc))

ggplot(df[1:10,], aes(x = reorder(loc,abundance_loc), y = abundance_loc)) +
  geom_col() +
  coord_flip() +
  theme_classic()
```

# Methylation

```{r}
df <- human_ptms_loc %>%
  filter(human_ptms_loc$unimod_id == 34) %>% 
  group_by(loc) %>% summarise(abundance_loc = sum(total_counts/18276619)) %>%
  arrange(desc(abundance_loc))

ggplot(df[1:20,], aes(x = reorder(loc,abundance_loc), y = abundance_loc)) +
  geom_col() +
  coord_flip() +
  theme_classic()
```

# All together

```{r}

df <- human_ptms_loc %>%
  mutate(mod_group = case_when(
    unimod_id == 1 ~'Acetyl', 
    unimod_id == 35 ~'Oxidation', 
    unimod_id == 21 ~'Phosphorylation',
    unimod_id == 34 ~'Methylation',
    unimod_id %in% oxPTMs$unimod_id & ptm_res %in% oxPTMs$AAs_list ~ 'oxPTMs',
    TRUE ~ "-"
  )) %>% filter(!mod_group == '-')

df <- df %>% group_by(loc, mod_group) %>% summarise(unimod_id, abundance_loc = sum(total_counts)) %>% 
  filter(loc == 'cytosol [GO:0005829]' | loc == 'extracellular exosome [GO:0070062]' | loc == 'cytoplasm [GO:0005737]' | loc == 'nucleus [GO:0005634]')

mod_group_colours <- c('Acetyl' = '#EA7317', 'Phosphorylation' = '#FFB703', 'Oxidation' = '#5DB7B1', '-' = '#3DA5D9', 'Methylation' = '#2364AA', 'oxPTMs' = '#5A2A82')

totals <- human_ptms_loc %>% group_by(unimod_id) %>%
  summarise(totals = sum(total_counts))

df <- inner_join(df, totals, by = join_by(unimod_id)) %>% mutate(prop = abundance_loc/totals) %>% distinct()

# Plot bar chart
ggplot(df, aes(x = loc, y = prop, fill = mod_group)) +
  geom_bar(stat = "identity", position = 'dodge') +
  scale_fill_manual(values = mod_group_colours, name = 'Key') +
  coord_flip()+
  labs(x = "Protein localisation",
       y = "Mean sum of normalised PTM counts") +
  theme_classic(base_size = 11)
```
